### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by marcemira** [huafu/ember-img-cache#1]
Any chances to add events like complete, fail, progress? Something like this:

{{img src onComplete=fadeId fail=showNiImg progress=showProgress }}

This would be very usefull! Thanks in advance

**Comment by huafu** [comment]
Hi @marcemira, I know it might be a bit late, but I hadn't time to work on this before now. I tried to add some few features, but I ended up re-writing totally the plugin as [ember-img-manager](https://github.com/huafu/ember-img-manager) with tons more features as well as the events. Check it out ;-)
